### ISSUE TITLE
Release the mt6737 from the nougat-7.1.1-release-woods

### ISSUE THREAD

**Issue by ghost** [MotorolaMobilityLLC/device-mediatek#1]
Hello,
Could you please release the mt6737, it's also a Cortex A53. And it would help the community to have this device tree available.

**Comment by LinuxPanda** [comment]
@yangqh5 @hangfan1

Please release mt6737 device tree for panelli too.

**Comment by ghost** [comment]
I don't think they want to release it @LinuxPanda.
👎 Motorola, you do NOT like open source!

**Comment by chenyt9** [comment]
@ioanmoldovan ,
Do you want the kernel code? Our mtk-kernel code is placed in another repo, which was released long ago. as follows:
https://github.com/MotorolaMobilityLLC/kernel-mtk/tree/nougat-7.1.1-release-woods

**Comment by ghost** [comment]
No I want the device tree.
The full config files to build AOSP

**Comment by LinuxPanda** [comment]
@chenyt9, We want the device tree for MT6737.

MT6757 was released here, https://github.com/MotorolaMobilityLLC/device-mediatek/tree/nougat-7.1.1-release-marino
MT6797 was released here, https://github.com/MotorolaMobilityLLC/device-mediatek/tree/nougat-7.1.1-release-manning

But where is MT6737?

**Comment by chenyt9** [comment]
Please Refer to this branch：
https://github.com/MotorolaMobilityLLC/device-mediatek/tree/nougat-7.1.1-release-woods
thanks.

**Comment by ghost** [comment]
Woods is mt6737 NOT mt6735. You published the wrong tree!

**Comment by chenyt9** [comment]
I have already confirmed that this code is correct. As for why it is written as mt6735 in the source code，  I don't know why.

**Comment by chenyt9** [comment]
@ioanmoldovan , Please see the log , all the patch is mt6737.

**Comment by LinuxPanda** [comment]
@ioanmoldovan Both woods & panelli use mt6737 board but the software platform is mt6735/mt6735m so the device tree is correct

**Comment by ghost** [comment]
Ahhh! Thanks!
